export const adminListingsCopy = {
	de: {
		administration: "Administration",
		all: "Alle",
		apartment: "Wohnung",
		archiveOutcome: "Archivgrund",
		archived: "Archiviert",
		city: "Stadt",
		create: "Inserat anlegen",
		createFirstListing: "Erstes Inserat anlegen",
		createFirstProperty: "Erste Immobilie anlegen",
		draft: "Entwurf",
		empty: "Keine Inserate entsprechen den aktuellen Filtern.",
		emptyListingsDescription:
			"Ihre Immobilien sind bereit. Legen Sie jetzt das erste Verkaufs- oder Vermietungsinserat an.",
		emptyListingsTitle: "Noch keine Inserate",
		emptyPropertiesDescription:
			"Ein Inserat benötigt zuerst eine Immobilie mit ihren internen Stammdaten.",
		emptyPropertiesTitle: "Zuerst eine Immobilie anlegen",
		house: "Haus",
		listing: "Inserat",
		listingType: "Vermarktungsart",
		locale: "de-DE",
		maxPrice: "Maximalpreis",
		minPrice: "Mindestpreis",
		missingImage: "Kein Titelbild",
		next: "Weiter",
		noPrice: "Preis fehlt",
		pageSize: "Pro Seite",
		previous: "Zurück",
		published: "Veröffentlicht",
		rent: "Vermietung",
		rented: "Vermietet",
		reset: "Filter zurücksetzen",
		resultCount: (count: number) => `${count} Inserate`,
		sale: "Verkauf",
		search: "Titel, Slug, Referenz, Stadt oder Straße suchen",
		sold: "Verkauft",
		sort: {
			newest: "Neueste zuerst",
			oldest: "Älteste zuerst",
			price_asc: "Preis aufsteigend",
			price_desc: "Preis absteigend",
			published_newest: "Zuletzt veröffentlicht",
			recently_updated: "Zuletzt bearbeitet",
			title_asc: "Titel A–Z",
			title_desc: "Titel Z–A",
		},
		status: "Status",
		subtitle:
			"Verwalten Sie Entwürfe, veröffentlichte Angebote und die archivierte Historie.",
		table: {
			address: "Immobilie",
			price: "Preis",
			status: "Status",
			title: "Inserat",
			updated: "Bearbeitet",
		},
		title: "Inserate",
		untitled: "Unbenanntes Inserat",
		view: "Inserat öffnen",
		withdrawn: "Zurückgezogen",
	},
	en: {
		administration: "Administration",
		all: "All",
		apartment: "Apartment",
		archiveOutcome: "Archive outcome",
		archived: "Archived",
		city: "City",
		create: "Create listing",
		createFirstListing: "Create first listing",
		createFirstProperty: "Create first property",
		draft: "Draft",
		empty: "No listings match the current filters.",
		emptyListingsDescription:
			"Your properties are ready. Create the first sale or rental listing.",
		emptyListingsTitle: "No listings yet",
		emptyPropertiesDescription:
			"A listing needs a property record with its internal details first.",
		emptyPropertiesTitle: "Create a property first",
		house: "House",
		listing: "Listing",
		listingType: "Listing type",
		locale: "en-GB",
		maxPrice: "Maximum price",
		minPrice: "Minimum price",
		missingImage: "No cover image",
		next: "Next",
		noPrice: "Price missing",
		pageSize: "Per page",
		previous: "Previous",
		published: "Published",
		rent: "Rent",
		rented: "Rented",
		reset: "Reset filters",
		resultCount: (count: number) => `${count} listings`,
		sale: "Sale",
		search: "Search title, slug, reference, city, or street",
		sold: "Sold",
		sort: {
			newest: "Newest first",
			oldest: "Oldest first",
			price_asc: "Price ascending",
			price_desc: "Price descending",
			published_newest: "Recently published",
			recently_updated: "Recently updated",
			title_asc: "Title A–Z",
			title_desc: "Title Z–A",
		},
		status: "Status",
		subtitle: "Manage drafts, published offers, and the archived history.",
		table: {
			address: "Property",
			price: "Price",
			status: "Status",
			title: "Listing",
			updated: "Updated",
		},
		title: "Listings",
		untitled: "Untitled listing",
		view: "Open listing",
		withdrawn: "Withdrawn",
	},
} as const;

export type AdminListingsCopy =
	(typeof adminListingsCopy)[keyof typeof adminListingsCopy];
