export const adminListingDetailsCopy = {
	de: {
		administration: "Administration · Inserate",
		archive: "Inserat archivieren",
		archiveDescription:
			"Wählen Sie den endgültigen Ausgang. Diese Aktion kann derzeit nicht rückgängig gemacht werden.",
		archiveOutcome: "Ergebnis",
		archiveTitle: "Inserat wirklich archivieren?",
		archived: "Archiviert",
		archivedAt: "Archiviert am",
		automatic: "Automatisch aus dem Inseratsinhalt",
		automaticDescription: "Verwendet die Inseratsbeschreibung",
		automaticSlug:
			"Automatisch aus dem Inseratstitel erzeugt. Das Feld oben kann den Wert überschreiben.",
		automaticTitle: "Verwendet den Inseratstitel",
		back: "Zurück zu Inseraten",
		blockers: {
			coverImage: "Titelbild hinzufügen",
			description: "Beschreibung ergänzen",
			price: "Preis ergänzen",
			title: "Titel ergänzen",
		},
		cancel: "Abbrechen",
		confirmArchive: "Archivierung bestätigen",
		confirmDelete: "Entwurf dauerhaft löschen",
		confirmPublish: "Jetzt veröffentlichen",
		content: "Öffentlicher Inhalt",
		customDescription: "Eigene SEO-Beschreibung",
		customSlug: "Eigener, bearbeiteter Slug",
		customTitle: "Eigener SEO-Titel",
		coverImage: "Titelbild",
		coverSaved: "Titelbild aktualisiert.",
		delete: "Entwurf löschen",
		deleteDescription:
			"Nur dieser Inseratentwurf wird gelöscht. Immobilie, Bilder und Merkmale bleiben erhalten.",
		deleteTitle: "Inseratentwurf löschen?",
		description: "Beschreibung",
		draft: "Entwurf",
		exactAddress: "Genaue Adresse öffentlich anzeigen",
		exactAddressHidden: "Straße und Hausnummer bleiben öffentlich verborgen.",
		exactAddressVisible: "Die vollständige Adresse wird öffentlich angezeigt.",
		features: "Immobilienmerkmale",
		featuresEmpty: "Keine Merkmale ausgewählt.",
		featuresSaved: "Immobilienmerkmale aktualisiert.",
		images: "Immobilienbilder",
		imagesExplanation:
			"Bilder und Titelbild gehören zur Immobilie und werden von ihren Inseraten gemeinsam verwendet.",
		listingType: "Vermarktungsart",
		editFeatures: "Merkmale bearbeiten",
		editImages: "Bilder bearbeiten",
		featureManager: {
			available: "Verfügbare Merkmale",
			clear: "Auswahl löschen",
			create: "Merkmal erstellen",
			createDescription:
				"Das neue Merkmal wird erstellt und direkt für diese Immobilie ausgewählt.",
			createTitle: "Neues Merkmal",
			description:
				"Wählen Sie bestehende Merkmale aus oder erstellen Sie ein neues. Die Auswahl gilt für alle Inserate dieser Immobilie.",
			duplicate: "Ein Merkmal mit diesem Namen ist bereits vorhanden.",
			empty: "Noch keine Merkmale ausgewählt.",
			name: "Name des Merkmals",
			namePlaceholder: "Zum Beispiel: Dachterrasse",
			noResults: "Keine passenden Merkmale gefunden.",
			remove: "Merkmal entfernen",
			required: "Geben Sie einen Namen ein.",
			save: "Merkmale speichern",
			search: "Merkmale suchen",
			selected: (count: number) => `${count} ausgewählt`,
			selectedTitle: "Ausgewählte Merkmale",
			title: "Immobilienmerkmale bearbeiten",
		},
		imageManager: {
			addFiles: "Bilder auswählen",
			altPlaceholder: "Beschreiben Sie, was auf dem Bild zu sehen ist",
			altText: "Alternativtext",
			capacity: (count: number) => `${count} von 30 Bildern`,
			cover: "Titelbild",
			description:
				"Laden Sie bis zu 30 Bilder hoch, bestimmen Sie das Titelbild und ordnen Sie die Galerie. Änderungen gelten für alle Inserate dieser Immobilie.",
			dragHint: "Ziehen oder mit den Pfeilen verschieben",
			dropActive: "Bilder hier ablegen",
			dropIdle: "Bilder hierher ziehen oder vom Gerät auswählen",
			emptyDescription:
				"Fügen Sie das erste Bild hinzu. Das erste erfolgreiche Bild wird automatisch zum Titelbild.",
			emptyTitle: "Noch keine Immobilienbilder",
			invalidType: "Verwenden Sie nur JPEG-, PNG- oder WebP-Bilder.",
			moveNext: "Bild nach hinten verschieben",
			movePrevious: "Bild nach vorne verschieben",
			remove: "Bild entfernen",
			save: "Bilder speichern",
			setCover: "Als Titelbild verwenden",
			supported: "JPEG, PNG oder WebP · max. 10 MB je Bild · max. 30 Bilder",
			title: "Immobilienbilder bearbeiten",
			tooLarge: "Das Bild darf maximal 10 MB groß sein.",
			tooMany: "Eine Immobilie kann höchstens 30 Bilder enthalten.",
			unsaved: "Änderungen werden erst mit „Bilder speichern“ übernommen.",
		},
		imagesSaved: "Immobilienbilder aktualisiert.",
		media: "Medien und Immobilie",
		noCover: "Kein Titelbild vorhanden",
		noPublicPage: "Die öffentliche Seite ist nicht mehr verfügbar.",
		notFound: "Dieses Inserat wurde nicht gefunden.",
		openProperty: "Immobilie öffnen",
		openPublic: "Öffentliches Inserat öffnen",
		preview: "Vorschau öffnen",
		priceRent: "Monatliche Kaltmiete",
		priceSale: "Kaufpreis",
		quickCoverDescription:
			"Wählen Sie ein vorhandenes Immobilienbild oder laden Sie ein neues Titelbild hoch.",
		quickCoverDrop: "Bild hier ablegen oder vom Gerät auswählen",
		quickCoverExisting: "Vorhandene Immobilienbilder",
		quickCoverFormats: "JPEG, PNG oder WebP · maximal 10 MB",
		quickCoverInvalidType: "Verwenden Sie ein JPEG-, PNG- oder WebP-Bild.",
		quickCoverSave: "Als Titelbild verwenden",
		quickCoverTitle: "Titelbild auswählen",
		quickCoverTooLarge: "Das Bild darf maximal 10 MB groß sein.",
		publish: "Inserat veröffentlichen",
		publishChecklist: "Voraussetzungen vor der Veröffentlichung",
		publishDescription:
			"Das Inserat wird sofort sichtbar. Inhalt und Preis bleiben bearbeitbar, der Slug wird jedoch festgeschrieben.",
		publishTitle: "Inserat veröffentlichen?",
		publishOptional:
			"URL-Slug, Adressfreigabe und SEO bleiben optional und sind im Formular sichtbar.",
		saveBeforePublish: "Speichern Sie zuerst Ihre aktuellen Änderungen.",
		published: "Veröffentlicht",
		publishedAt: "Veröffentlicht am",
		publicUrl: "Öffentliche URL",
		readiness: "Veröffentlichungsbereitschaft",
		ready: "Bereit zur Veröffentlichung",
		rent: "Vermietung",
		rented: "Vermietet",
		sale: "Verkauf",
		save: "Änderungen speichern",
		saved: "Änderungen gespeichert.",
		saving: "Wird gespeichert",
		seo: "SEO-Einstellungen",
		seoDescription: "SEO-Beschreibung",
		seoHelp:
			"Leere Felder folgen automatisch dem aktuellen Titel und der Beschreibung.",
		seoTitle: "SEO-Titel",
		seoPreview: "Vorschau für Suchmaschinen",
		slug: "URL-Slug",
		sold: "Verkauft",
		status: "Status",
		subtitle:
			"Inhalt, Veröffentlichung und Historie dieses Inserats verwalten.",
		title: "Inseratstitel",
		unavailablePreview: "Speichern Sie Änderungen vor der Vorschau.",
		updatedAt: "Zuletzt bearbeitet",
		urlPreview: "Vorschau der öffentlichen URL",
		withdrawn: "Zurückgezogen",
	},
	en: {
		administration: "Administration · Listings",
		archive: "Archive listing",
		archiveDescription:
			"Choose the final outcome. This action cannot currently be reversed.",
		archiveOutcome: "Outcome",
		archiveTitle: "Archive this listing?",
		archived: "Archived",
		archivedAt: "Archived at",
		automatic: "Automatically follows the listing content",
		automaticDescription: "Uses the listing description",
		automaticSlug:
			"Generated automatically from the listing title. The field above can override it.",
		automaticTitle: "Uses the listing title",
		back: "Back to listings",
		blockers: {
			coverImage: "Add a cover image",
			description: "Add a description",
			price: "Add a price",
			title: "Add a title",
		},
		cancel: "Cancel",
		confirmArchive: "Confirm archive",
		confirmDelete: "Delete draft permanently",
		confirmPublish: "Publish now",
		content: "Public content",
		customDescription: "Custom SEO description",
		customSlug: "Custom editable slug",
		customTitle: "Custom SEO title",
		coverImage: "Cover image",
		coverSaved: "Cover image updated.",
		delete: "Delete draft",
		deleteDescription:
			"Only this listing draft is deleted. The property, images, and features remain.",
		deleteTitle: "Delete listing draft?",
		description: "Description",
		draft: "Draft",
		exactAddress: "Show exact address publicly",
		exactAddressHidden: "Street and house number remain hidden publicly.",
		exactAddressVisible: "The complete address is shown publicly.",
		features: "Property features",
		featuresEmpty: "No features selected.",
		featuresSaved: "Property features updated.",
		images: "Property images",
		imagesExplanation:
			"Images and the cover belong to the property and are shared by its listings.",
		listingType: "Listing type",
		editFeatures: "Edit features",
		editImages: "Edit images",
		featureManager: {
			available: "Available features",
			clear: "Clear selection",
			create: "Create feature",
			createDescription:
				"The new feature will be created and selected for this property immediately.",
			createTitle: "New feature",
			description:
				"Select existing features or create a new one. The selection applies to every listing for this property.",
			duplicate: "A feature with this name already exists.",
			empty: "No features selected yet.",
			name: "Feature name",
			namePlaceholder: "For example: Roof terrace",
			noResults: "No features match this search.",
			remove: "Remove feature",
			required: "Enter a feature name.",
			save: "Save features",
			search: "Search features",
			selected: (count: number) => `${count} selected`,
			selectedTitle: "Selected features",
			title: "Edit property features",
		},
		imageManager: {
			addFiles: "Choose images",
			altPlaceholder: "Describe what is visible in this image",
			altText: "Alternative text",
			capacity: (count: number) => `${count} of 30 images`,
			cover: "Cover",
			description:
				"Upload up to 30 images, choose the cover, and arrange the gallery. Changes apply to every listing for this property.",
			dragHint: "Drag or use the arrow controls to reorder",
			dropActive: "Drop images here",
			dropIdle: "Drag images here or choose them from your device",
			emptyDescription:
				"Add the first image. The first successful image automatically becomes the cover.",
			emptyTitle: "No property images yet",
			invalidType: "Use JPEG, PNG, or WebP images only.",
			moveNext: "Move image later",
			movePrevious: "Move image earlier",
			remove: "Remove image",
			save: "Save images",
			setCover: "Use as cover",
			supported: "JPEG, PNG, or WebP · max 10 MB each · max 30 images",
			title: "Edit property images",
			tooLarge: "The image must not exceed 10 MB.",
			tooMany: "A property can contain no more than 30 images.",
			unsaved: "Changes apply only after you choose “Save images.”",
		},
		imagesSaved: "Property images updated.",
		media: "Media and property",
		noCover: "No cover image available",
		noPublicPage: "The public page is no longer available.",
		notFound: "This listing could not be found.",
		openProperty: "Open property",
		openPublic: "Open public listing",
		preview: "Open preview",
		priceRent: "Monthly base rent",
		priceSale: "Purchase price",
		quickCoverDescription:
			"Choose an existing property image or upload a new cover without leaving this listing.",
		quickCoverDrop: "Drop an image here or choose it from your device",
		quickCoverExisting: "Existing property images",
		quickCoverFormats: "JPEG, PNG, or WebP · maximum 10 MB",
		quickCoverInvalidType: "Use a JPEG, PNG, or WebP image.",
		quickCoverSave: "Use as cover",
		quickCoverTitle: "Choose a cover image",
		quickCoverTooLarge: "The image must not exceed 10 MB.",
		publish: "Publish listing",
		publishChecklist: "Requirements before publishing",
		publishDescription:
			"The listing becomes visible immediately. Content and price stay editable, while the slug becomes fixed.",
		publishTitle: "Publish this listing?",
		publishOptional:
			"URL slug, address visibility, and SEO remain optional and visible in the form.",
		saveBeforePublish: "Save your current changes first.",
		published: "Published",
		publishedAt: "Published at",
		publicUrl: "Public URL",
		readiness: "Publication readiness",
		ready: "Ready to publish",
		rent: "Rent",
		rented: "Rented",
		sale: "Sale",
		save: "Save changes",
		saved: "Changes saved.",
		saving: "Saving",
		seo: "SEO settings",
		seoDescription: "SEO description",
		seoHelp:
			"Blank fields automatically follow the current title and description.",
		seoTitle: "SEO title",
		seoPreview: "Search result preview",
		slug: "URL slug",
		sold: "Sold",
		status: "Status",
		subtitle: "Manage this listing's content, publication, and history.",
		title: "Listing title",
		unavailablePreview: "Save changes before opening the preview.",
		updatedAt: "Last updated",
		urlPreview: "Public URL preview",
		withdrawn: "Withdrawn",
	},
} as const;

export type AdminListingDetailsCopy =
	(typeof adminListingDetailsCopy)[keyof typeof adminListingDetailsCopy];
