export const propertySetupCopy = {
	de: {
		journey: {
			complete: "Erledigt",
			current: "Aktuell",
			features: "Merkmale",
			images: "Bilder",
			listing: "Inserat",
			property: "Immobiliendaten",
			upcoming: "Danach",
		},
		common: {
			administration: "Administration · Immobilieneinrichtung",
			discard: "Änderungen verwerfen",
			finishLater: "Später fortsetzen",
			leaveDescription:
				"Ihre nicht gespeicherte Merkmalsauswahl geht verloren.",
			leaveTitle: "Einrichtung verlassen?",
			mockNotice: "Diese Vorschau speichert Änderungen nur lokal.",
			stay: "Hier bleiben",
		},
		images: {
			addFiles: "Bilder auswählen",
			altDescription:
				"Beschreiben Sie kurz, was auf dem Bild zu sehen ist. Dateinamen müssen nicht wiederholt werden.",
			altLabel: "Alternativtext (optional)",
			altTitle: "Alternativtext bearbeiten",
			cancel: "Abbrechen",
			capacity: (used: number) => `${used} von 30 Bildern`,
			continue: "Weiter zu Merkmalen",
			cover: "Titelbild",
			delete: "Bild löschen",
			deleteCover:
				"Das erste verbleibende Bild wird automatisch zum neuen Titelbild.",
			deleteDescription: "Dieses Bild wird aus der Immobilie entfernt.",
			deleteTitle: "Bild wirklich löschen?",
			description:
				"Laden Sie mehrere Ansichten hoch, bestimmen Sie das Titelbild und ordnen Sie die Galerie.",
			dropActive: "Bilder hier ablegen",
			dropIdle: "Bilder hierher ziehen oder vom Gerät auswählen",
			empty: "Noch keine Bilder hochgeladen.",
			errorTooLarge: "Die Datei überschreitet 10 MB.",
			errorTooMany: "Die Immobilie kann höchstens 30 Bilder enthalten.",
			errorType: "Nur JPEG, PNG und WebP werden unterstützt.",
			failed: "Upload fehlgeschlagen",
			makeCover: "Als Titelbild festlegen",
			moveNext: "Nach hinten verschieben",
			movePrevious: "Nach vorne verschieben",
			remove: "Entfernen",
			retry: "Erneut versuchen",
			save: "Speichern",
			success: "Immobilie angelegt",
			supported: "JPEG, PNG oder WebP · maximal 10 MB pro Datei",
			title: "Immobilienbilder",
			uploaded: "Hochgeladen",
			uploading: "Wird hochgeladen",
			waiting: "Wartet",
		},
		features: {
			cancel: "Abbrechen",
			clear: "Auswahl löschen",
			codeHint: "Der stabile Merkmalscode wird automatisch erzeugt.",
			conflict: "Ein Merkmal mit diesem Namen existiert bereits.",
			create: "Neues Merkmal",
			createAction: "Merkmal anlegen",
			createDescription:
				"Das neue Merkmal wird dem Katalog hinzugefügt und direkt ausgewählt.",
			createTitle: "Merkmal anlegen",
			description:
				"Wählen Sie alle Merkmale aus, die dauerhaft zu dieser Immobilie gehören.",
			empty: "Der Merkmalskatalog ist noch leer.",
			name: "Name",
			noResults: "Keine Merkmale entsprechen der Suche.",
			required: "Bitte geben Sie einen Namen ein.",
			save: "Merkmale speichern und fortfahren",
			saving: "Merkmale werden gespeichert",
			search: "Merkmale nach Name oder Code suchen",
			selected: (count: number) => `${count} ausgewählt`,
			success: "Merkmale wurden gespeichert.",
			title: "Immobilienmerkmale",
		},
	},
	en: {
		journey: {
			complete: "Complete",
			current: "Current",
			features: "Features",
			images: "Images",
			listing: "Listing",
			property: "Property details",
			upcoming: "Upcoming",
		},
		common: {
			administration: "Administration · Property setup",
			discard: "Discard changes",
			finishLater: "Finish later",
			leaveDescription: "Your unsaved feature selection will be lost.",
			leaveTitle: "Leave property setup?",
			mockNotice: "This preview stores changes locally only.",
			stay: "Stay here",
		},
		images: {
			addFiles: "Choose images",
			altDescription:
				"Briefly describe what the image shows. There is no need to repeat the filename.",
			altLabel: "Alternative text (optional)",
			altTitle: "Edit alternative text",
			cancel: "Cancel",
			capacity: (used: number) => `${used} of 30 images`,
			continue: "Continue to features",
			cover: "Cover",
			delete: "Delete image",
			deleteCover:
				"The first remaining image will automatically become the new cover.",
			deleteDescription: "This image will be removed from the property.",
			deleteTitle: "Delete this image?",
			description:
				"Upload several views, choose the cover, and arrange the gallery order.",
			dropActive: "Drop images here",
			dropIdle: "Drag images here or choose them from your device",
			empty: "No images uploaded yet.",
			errorTooLarge: "The file is larger than 10 MB.",
			errorTooMany: "A property can contain no more than 30 images.",
			errorType: "Only JPEG, PNG, and WebP are supported.",
			failed: "Upload failed",
			makeCover: "Make cover",
			moveNext: "Move later",
			movePrevious: "Move earlier",
			remove: "Remove",
			retry: "Retry",
			save: "Save",
			success: "Property created",
			supported: "JPEG, PNG, or WebP · maximum 10 MB per file",
			title: "Property images",
			uploaded: "Uploaded",
			uploading: "Uploading",
			waiting: "Waiting",
		},
		features: {
			cancel: "Cancel",
			clear: "Clear selection",
			codeHint: "The stable feature code is generated automatically.",
			conflict: "A feature with this name already exists.",
			create: "Create new feature",
			createAction: "Create feature",
			createDescription:
				"The new feature is added to the catalog and selected immediately.",
			createTitle: "Create feature",
			description:
				"Select every feature that permanently belongs to this property.",
			empty: "The feature catalog is empty.",
			name: "Name",
			noResults: "No features match this search.",
			required: "Enter a feature name.",
			save: "Save features and continue",
			saving: "Saving features",
			search: "Search features by name or code",
			selected: (count: number) => `${count} selected`,
			success: "Features saved.",
			title: "Property features",
		},
	},
} as const;
