export const adminPropertyDetailsCopy = {
	de: {
		active: "Aktiv",
		administration: "Administration · Immobilienakte",
		agencyOwned: "Agenturbestand",
		archive: "Immobilie archivieren",
		archiveDescription:
			"Archivieren ist nur möglich, wenn keine offenen Inserate vorhanden sind.",
		archiveTitle: "Immobilie archivieren?",
		archived: "Archiviert",
		back: "Alle Immobilien",
		cancel: "Abbrechen",
		contact: "Eigentümer und Quelle",
		delete: "Dauerhaft löschen",
		deleteDescription:
			"Die Löschung ist endgültig und kann vom Backend abgelehnt werden, wenn die Immobilie bereits öffentlich verwendet wurde.",
		deleteTitle: "Immobilie dauerhaft löschen?",
		edit: "Immobilie bearbeiten",
		external: "Externer Auftrag",
		features: "Merkmale verwalten",
		field: {
			bathrooms: "Bäder",
			bedrooms: "Schlafzimmer",
			city: "Stadt",
			floor: "Etage",
			houseNumber: "Hausnummer",
			livingArea: "Wohnfläche",
			plotArea: "Grundstücksfläche",
			postalCode: "Postleitzahl",
			rooms: "Zimmer",
			street: "Straße",
			totalFloors: "Etagen insgesamt",
			unit: "Einheit",
			yearBuilt: "Baujahr",
		},
		images: "Bilder verwalten",
		listings: "Inserate",
		listingsDescription:
			"Öffnen Sie den Inserate-Bereich, um Entwürfe, Veröffentlichungen und Archivierungen für diese Immobilie zu verwalten.",
		notFound: "Diese Immobilie wurde nicht gefunden.",
		property: "Immobiliendaten",
		required: "Dieses Feld ist erforderlich.",
		restore: "Immobilie wiederherstellen",
		restoreDescription:
			"Die Immobilie wird wieder für Verwaltungsaktionen verfügbar.",
		restoreTitle: "Immobilie wiederherstellen?",
		save: "Änderungen speichern",
		saving: "Änderungen werden gespeichert",
		source: "Quelle",
		success: "Immobiliendaten wurden aktualisiert.",
		title: "Immobilienakte",
		typeApartment: "Wohnung",
		typeHouse: "Haus",
		updated: "Zuletzt aktualisiert",
	},
	en: {
		active: "Active",
		administration: "Administration · Property record",
		agencyOwned: "Agency-owned",
		archive: "Archive property",
		archiveDescription:
			"Archiving is available only when the property has no open listings.",
		archiveTitle: "Archive this property?",
		archived: "Archived",
		back: "All properties",
		cancel: "Cancel",
		contact: "Owner and source",
		delete: "Delete permanently",
		deleteDescription:
			"Deletion is permanent and the backend may reject it when the property has already entered the public workflow.",
		deleteTitle: "Delete this property permanently?",
		edit: "Edit property",
		external: "External client",
		features: "Manage features",
		field: {
			bathrooms: "Bathrooms",
			bedrooms: "Bedrooms",
			city: "City",
			floor: "Floor number",
			houseNumber: "House number",
			livingArea: "Living area",
			plotArea: "Plot area",
			postalCode: "Postal code",
			rooms: "Rooms",
			street: "Street name",
			totalFloors: "Total floors",
			unit: "Unit number",
			yearBuilt: "Year built",
		},
		images: "Manage images",
		listings: "Listings",
		listingsDescription:
			"Open the Listings workspace to manage drafts, publication, and archive status for this property.",
		notFound: "This property could not be found.",
		property: "Property details",
		required: "This field is required.",
		restore: "Restore property",
		restoreDescription:
			"The property becomes available for management actions again.",
		restoreTitle: "Restore this property?",
		save: "Save changes",
		saving: "Saving changes",
		source: "Source",
		success: "Property details updated.",
		title: "Property record",
		typeApartment: "Apartment",
		typeHouse: "House",
		updated: "Last updated",
	},
} as const;
