import type {
	PropertyFeatureOption,
	PropertySearchListing,
} from "@/frontend/features/listings/listing.types";

export const mockPropertyFeatures: PropertyFeatureOption[] = [
	{ id: "balcony", label: { de: "Balkon", en: "Balcony" } },
	{ id: "garden", label: { de: "Garten", en: "Garden" } },
	{ id: "parking", label: { de: "Stellplatz", en: "Parking" } },
	{ id: "elevator", label: { de: "Aufzug", en: "Elevator" } },
	{
		id: "fitted-kitchen",
		label: { de: "Einbauküche", en: "Fitted kitchen" },
	},
	{ id: "terrace", label: { de: "Terrasse", en: "Terrace" } },
	{ id: "cellar", label: { de: "Keller", en: "Cellar" } },
	{
		id: "accessible",
		label: { de: "Barrierearm", en: "Accessible" },
	},
];

export const mockPropertyListings: PropertySearchListing[] = [
	{
		id: "search-01",
		slug: "modernes-familienhaus-erfurt",
		title: {
			de: "Modernes Familienhaus mit ruhigem Garten",
			en: "Modern family home with a quiet garden",
		},
		city: "Erfurt",
		postalCode: "99094",
		price: 435000,
		rooms: 5,
		bedrooms: 3,
		livingArea: 148,
		propertyType: "HOUSE",
		listingType: "SALE",
		featureIds: ["garden", "parking", "terrace", "cellar"],
		image: {
			src: "/images/properties/modern-home-erfurt.jpg",
			alt: {
				de: "Modernes Familienhaus mit Garten in Erfurt",
				en: "Modern family home with a garden in Erfurt",
			},
		},
	},
	{
		id: "search-02",
		slug: "helle-wohnung-erfurt-innenstadt",
		title: {
			de: "Helle Wohnung nahe der Erfurter Innenstadt",
			en: "Bright apartment close to Erfurt city centre",
		},
		city: "Erfurt",
		postalCode: "99084",
		price: 285000,
		rooms: 3,
		bedrooms: 2,
		livingArea: 82,
		propertyType: "APARTMENT",
		listingType: "SALE",
		featureIds: ["balcony", "elevator", "cellar"],
		image: {
			src: "/images/properties/erfurt-apartment.jpg",
			alt: {
				de: "Wohnhaus mit Balkonen in Erfurt",
				en: "Apartment building with balconies in Erfurt",
			},
		},
	},
	{
		id: "search-03",
		slug: "ruhige-wohnung-weimar",
		title: {
			de: "Ruhige Wohnung mit lichtdurchflutetem Wohnbereich",
			en: "Calm apartment with a light-filled living space",
		},
		city: "Weimar",
		postalCode: "99423",
		price: 980,
		rooms: 2,
		bedrooms: 1,
		livingArea: 64,
		propertyType: "APARTMENT",
		listingType: "RENT",
		featureIds: ["balcony", "fitted-kitchen"],
		image: {
			src: "/images/properties/weimar-apartment.jpg",
			alt: {
				de: "Lichtdurchfluteter Wohnbereich in Weimar",
				en: "Light-filled living area in Weimar",
			},
		},
	},
	{
		id: "search-04",
		slug: "grosszuegiges-wohnhaus-jena",
		title: {
			de: "Zeitgemäßes Wohnhaus mit großzügigen Räumen",
			en: "Contemporary residence with generous rooms",
		},
		city: "Jena",
		postalCode: "07743",
		price: 520000,
		rooms: 5,
		bedrooms: 4,
		livingArea: 156,
		propertyType: "HOUSE",
		listingType: "SALE",
		featureIds: ["garden", "parking", "terrace"],
		image: {
			src: "/images/properties/jena-residence.jpg",
			alt: {
				de: "Zeitgemäßes Wohnhaus in Jena",
				en: "Contemporary residence in Jena",
			},
		},
	},
	{
		id: "search-05",
		slug: "komfortable-wohnung-gotha",
		title: {
			de: "Wohnliche Wohnung für einen komfortablen Alltag",
			en: "Warm apartment designed for everyday comfort",
		},
		city: "Gotha",
		postalCode: "99867",
		price: 1350,
		rooms: 4,
		bedrooms: 3,
		livingArea: 108,
		propertyType: "APARTMENT",
		listingType: "RENT",
		featureIds: ["balcony", "parking", "fitted-kitchen"],
		image: {
			src: "/images/properties/gotha-apartment.jpg",
			alt: {
				de: "Helle Wohnung in Gotha",
				en: "Bright apartment in Gotha",
			},
		},
	},
	{
		id: "search-06",
		slug: "freistehendes-haus-eisenach",
		title: {
			de: "Freistehendes Haus mit offenen Wohnbereichen",
			en: "Detached home with open living areas",
		},
		city: "Eisenach",
		postalCode: "99817",
		price: 369000,
		rooms: 4,
		bedrooms: 3,
		livingArea: 132,
		propertyType: "HOUSE",
		listingType: "SALE",
		featureIds: ["garden", "parking", "cellar"],
		image: {
			src: "/images/properties/eisenach-house.jpg",
			alt: {
				de: "Freistehendes Haus mit Garten in Eisenach",
				en: "Detached home with a garden in Eisenach",
			},
		},
	},
	{
		id: "search-07",
		slug: "ruhige-wohnung-gera",
		title: {
			de: "Gut angebundene Wohnung in ruhiger Nachbarschaft",
			en: "Well-connected apartment in a quiet neighbourhood",
		},
		city: "Gera",
		postalCode: "07545",
		price: 1150,
		rooms: 3,
		bedrooms: 2,
		livingArea: 88,
		propertyType: "APARTMENT",
		listingType: "RENT",
		featureIds: ["balcony", "elevator"],
		image: {
			src: "/images/properties/gera-apartment.jpg",
			alt: {
				de: "Wohngebäude mit Balkonen in Gera",
				en: "Apartment building with balconies in Gera",
			},
		},
	},
	{
		id: "search-08",
		slug: "gartenhaus-erfurt-daberstedt",
		title: {
			de: "Familienhaus mit Terrasse in Daberstedt",
			en: "Family home with terrace in Daberstedt",
		},
		city: "Erfurt",
		postalCode: "99099",
		price: 488000,
		rooms: 6,
		bedrooms: 4,
		livingArea: 171,
		propertyType: "HOUSE",
		listingType: "SALE",
		featureIds: ["garden", "terrace", "parking", "cellar"],
		image: {
			src: "/images/properties/modern-home-erfurt.jpg",
			alt: {
				de: "Familienhaus mit Terrasse in Erfurt",
				en: "Family home with a terrace in Erfurt",
			},
		},
	},
	{
		id: "search-09",
		slug: "stadtwohnung-erfurt-andreasvorstadt",
		title: {
			de: "Stadtwohnung mit Balkon in der Andreasvorstadt",
			en: "City apartment with balcony in Andreasvorstadt",
		},
		city: "Erfurt",
		postalCode: "99089",
		price: 1240,
		rooms: 3,
		bedrooms: 2,
		livingArea: 91,
		propertyType: "APARTMENT",
		listingType: "RENT",
		featureIds: ["balcony", "fitted-kitchen", "cellar"],
		image: {
			src: "/images/properties/erfurt-apartment.jpg",
			alt: {
				de: "Stadtwohnung mit Balkon in Erfurt",
				en: "City apartment with a balcony in Erfurt",
			},
		},
	},
	{
		id: "search-10",
		slug: "kompakte-wohnung-weimar-west",
		title: {
			de: "Kompakte Wohnung mit klarer Raumaufteilung",
			en: "Compact apartment with a practical layout",
		},
		city: "Weimar",
		postalCode: "99427",
		price: 760,
		rooms: 2,
		bedrooms: 1,
		livingArea: 52,
		propertyType: "APARTMENT",
		listingType: "RENT",
		featureIds: ["elevator", "accessible"],
		image: {
			src: "/images/properties/weimar-apartment.jpg",
			alt: {
				de: "Kompakte Wohnung in Weimar",
				en: "Compact apartment in Weimar",
			},
		},
	},
	{
		id: "search-11",
		slug: "einfamilienhaus-jena-lobeda",
		title: {
			de: "Einfamilienhaus mit weitem Blick über Jena",
			en: "Detached home with open views across Jena",
		},
		city: "Jena",
		postalCode: "07747",
		price: 465000,
		rooms: 5,
		bedrooms: 3,
		livingArea: 142,
		propertyType: "HOUSE",
		listingType: "SALE",
		featureIds: ["garden", "parking", "terrace"],
		image: {
			src: "/images/properties/jena-residence.jpg",
			alt: {
				de: "Einfamilienhaus mit weitem Blick in Jena",
				en: "Detached home with open views in Jena",
			},
		},
	},
	{
		id: "search-12",
		slug: "altbauwohnung-gotha-zentrum",
		title: {
			de: "Gepflegte Altbauwohnung nahe dem Gothaer Zentrum",
			en: "Well-kept period apartment near central Gotha",
		},
		city: "Gotha",
		postalCode: "99867",
		price: 219000,
		rooms: 3,
		bedrooms: 2,
		livingArea: 86,
		propertyType: "APARTMENT",
		listingType: "SALE",
		featureIds: ["balcony", "cellar"],
		image: {
			src: "/images/properties/gotha-apartment.jpg",
			alt: {
				de: "Gepflegte Altbauwohnung in Gotha",
				en: "Well-kept period apartment in Gotha",
			},
		},
	},
	{
		id: "search-13",
		slug: "mietshaus-eisenach-sued",
		title: {
			de: "Ruhiges Mietshaus mit privatem Garten",
			en: "Quiet rental home with a private garden",
		},
		city: "Eisenach",
		postalCode: "99817",
		price: 1680,
		rooms: 5,
		bedrooms: 3,
		livingArea: 139,
		propertyType: "HOUSE",
		listingType: "RENT",
		featureIds: ["garden", "parking", "terrace"],
		image: {
			src: "/images/properties/eisenach-house.jpg",
			alt: {
				de: "Ruhiges Mietshaus mit Garten in Eisenach",
				en: "Quiet rental home with a garden in Eisenach",
			},
		},
	},
	{
		id: "search-14",
		slug: "barrierearme-wohnung-gera",
		title: {
			de: "Barrierearme Wohnung mit sonnigem Balkon",
			en: "Accessible apartment with a sunny balcony",
		},
		city: "Gera",
		postalCode: "07546",
		price: 890,
		rooms: 2,
		bedrooms: 1,
		livingArea: 68,
		propertyType: "APARTMENT",
		listingType: "RENT",
		featureIds: ["balcony", "elevator", "accessible"],
		image: {
			src: "/images/properties/gera-apartment.jpg",
			alt: {
				de: "Barrierearme Wohnung mit Balkon in Gera",
				en: "Accessible apartment with a balcony in Gera",
			},
		},
	},
];
