export const adminInquiriesCopy = {
	de: {
		administration: "Administration",
		all: "Alle",
		archive: "Archivieren",
		archiveStatus: "Postfach",
		archived: "Archiviert",
		archivedAt: "Archiviert am",
		active: "Aktiv",
		back: "Zurück",
		buying: "Kaufen",
		close: "Schließen",
		closed: "Geschlossen",
		contact: "Kontaktdaten",
		contacted: "Kontaktiert",
		createdAt: "Eingegangen",
		description:
			"Allgemeine und objektbezogene Anfragen lesen und mit einem einfachen Bearbeitungsstatus verwalten.",
		detail: "Anfragedetails",
		email: "E-Mail",
		empty: "Keine Anfragen entsprechen den aktuellen Filtern.",
		error: "Die Anfragen konnten nicht geladen werden.",
		filterListing: "Inserat-ID",
		general: "Allgemein",
		inbox: "Aktives Postfach",
		interest: "Interesse",
		listing: "Inserat",
		listingReference: "Referenz",
		loading: "Anfragen werden geladen …",
		locale: "de-DE",
		markingRead: "Wird als gelesen markiert …",
		message: "Nachricht",
		mutationError: "Die Änderung konnte nicht gespeichert werden.",
		new: "Neu",
		newest: "Neueste zuerst",
		next: "Weiter",
		noPhone: "Nicht angegeben",
		oldest: "Älteste zuerst",
		pageSize: "Pro Seite",
		phone: "Telefon",
		previous: "Zurück",
		privacy: "Datenschutz",
		privacyAccepted: (version: string, date: string) =>
			`Akzeptiert (${version}) am ${date}`,
		read: "Gelesen",
		renting: "Mieten",
		reset: "Filter zurücksetzen",
		restore: "Wiederherstellen",
		retry: "Erneut versuchen",
		results: (count: number) => `${count} Anfragen`,
		saving: "Wird gespeichert …",
		status: "Bearbeitungsstatus",
		sort: "Sortierung",
		title: "Anfragen",
		type: "Anfragetyp",
		unavailableListing: "Inserat nicht mehr verfügbar",
		unread: "Ungelesen",
		unreadOnly: "Nur ungelesen",
		readOnly: "Nur gelesen",
		unauthorized:
			"Ihre Admin-Sitzung ist abgelaufen oder nicht berechtigt. Melden Sie sich erneut an.",
		updating: "Ergebnisse werden aktualisiert …",
	},
	en: {
		administration: "Administration",
		all: "All",
		archive: "Archive",
		archiveStatus: "Inbox",
		archived: "Archived",
		archivedAt: "Archived at",
		active: "Active",
		back: "Back",
		buying: "Buying",
		close: "Close",
		closed: "Closed",
		contact: "Contact details",
		contacted: "Contacted",
		createdAt: "Received",
		description:
			"Read general and listing enquiries and manage their small processing state.",
		detail: "Inquiry details",
		email: "Email",
		empty: "No inquiries match the current filters.",
		error: "The inquiries could not be loaded.",
		filterListing: "Listing ID",
		general: "General",
		inbox: "Active inbox",
		interest: "Interest",
		listing: "Listing",
		listingReference: "Reference",
		loading: "Loading inquiries…",
		locale: "en-GB",
		markingRead: "Marking as read…",
		message: "Message",
		mutationError: "The change could not be saved.",
		new: "New",
		newest: "Newest first",
		next: "Next",
		noPhone: "Not provided",
		oldest: "Oldest first",
		pageSize: "Per page",
		phone: "Phone",
		previous: "Previous",
		privacy: "Privacy",
		privacyAccepted: (version: string, date: string) =>
			`Accepted (${version}) on ${date}`,
		read: "Read",
		renting: "Renting",
		reset: "Reset filters",
		restore: "Restore",
		retry: "Try again",
		results: (count: number) => `${count} inquiries`,
		saving: "Saving…",
		status: "Processing status",
		sort: "Sort",
		title: "Inquiries",
		type: "Inquiry type",
		unavailableListing: "Listing no longer available",
		unread: "Unread",
		unreadOnly: "Unread only",
		readOnly: "Read only",
		unauthorized:
			"Your admin session has expired or is not authorized. Sign in again.",
		updating: "Updating results…",
	},
} as const;

export type AdminInquiriesCopy =
	(typeof adminInquiriesCopy)[keyof typeof adminInquiriesCopy];
