type Range = readonly [minimum: number, maximum: number];

export type SeedDistrict = {
	name: string;
	postalCode: string;
};

export type SeedCity = {
	name: string;
	/** Name used in hyphenated locations such as "Halle-Giebichenstein". */
	shortName: string;
	/** Exact number of demo properties generated in this city. */
	propertyCount: number;
	isMetropolitan: boolean;
	districts: readonly SeedDistrict[];
	streets: readonly string[];
	/** Asking prices in EUR per square metre of living area. */
	salePerM2: { apartment: Range; house: Range };
	/** Net cold rent in EUR per square metre and month. */
	rentPerM2: Range;
	transitStop: string;
	locationHighlight: string;
};

// Price ranges approximate the 2026 asking-price level of each market. They
// only need to be plausible for demo listings, not a market survey.
export const seedCities: readonly SeedCity[] = [
	{
		name: "Erfurt",
		shortName: "Erfurt",
		propertyCount: 110,
		isMetropolitan: false,
		districts: [
			{ name: "Altstadt", postalCode: "99084" },
			{ name: "Löbervorstadt", postalCode: "99096" },
			{ name: "Brühlervorstadt", postalCode: "99094" },
			{ name: "Andreasvorstadt", postalCode: "99089" },
			{ name: "Krämpfervorstadt", postalCode: "99085" },
			{ name: "Johannesvorstadt", postalCode: "99086" },
			{ name: "Daberstedt", postalCode: "99099" },
			{ name: "Hochheim", postalCode: "99094" },
			{ name: "Ilversgehofen", postalCode: "99089" },
			{ name: "Melchendorf", postalCode: "99097" },
		],
		streets: [
			"Johannesstraße",
			"Löberstraße",
			"Gothaer Straße",
			"Nordhäuser Straße",
			"Arnstädter Straße",
			"Magdeburger Allee",
			"Krämpferstraße",
			"Pförtchenstraße",
			"Hochheimer Straße",
			"Dalbergsweg",
			"Schillerstraße",
			"Windthorststraße",
			"Kartäuserstraße",
			"Wallstraße",
		],
		salePerM2: { apartment: [2700, 3900], house: [2500, 3700] },
		rentPerM2: [8.2, 11.5],
		transitStop: "Straßenbahnhaltestelle",
		locationHighlight:
			"Die Erfurter Altstadt mit Domplatz und Krämerbrücke ist schnell erreichbar, und der ICE-Knoten verbindet die Landeshauptstadt direkt mit Berlin, Frankfurt und München.",
	},
	{
		name: "Weimar",
		shortName: "Weimar",
		propertyCount: 60,
		isMetropolitan: false,
		districts: [
			{ name: "Altstadt", postalCode: "99423" },
			{ name: "Westvorstadt", postalCode: "99423" },
			{ name: "Nordvorstadt", postalCode: "99423" },
			{ name: "Parkvorstadt", postalCode: "99425" },
			{ name: "Südstadt", postalCode: "99425" },
			{ name: "Oberweimar", postalCode: "99425" },
			{ name: "Schöndorf", postalCode: "99427" },
			{ name: "West", postalCode: "99427" },
		],
		streets: [
			"Belvederer Allee",
			"Cranachstraße",
			"Humboldtstraße",
			"Trierer Straße",
			"Erfurter Straße",
			"Schwanseestraße",
			"Carl-August-Allee",
			"Bauhausstraße",
			"Marienstraße",
			"Jenaer Straße",
			"Wörthstraße",
		],
		salePerM2: { apartment: [2900, 4200], house: [2700, 3900] },
		rentPerM2: [8.5, 12],
		transitStop: "Bushaltestelle",
		locationHighlight:
			"Die Weimarer Innenstadt mit ihren Kulturstätten und der Park an der Ilm sind gut erreichbar, nach Erfurt und Jena bestehen schnelle Bahnverbindungen.",
	},
	{
		name: "Jena",
		shortName: "Jena",
		propertyCount: 70,
		isMetropolitan: false,
		districts: [
			{ name: "Zentrum", postalCode: "07743" },
			{ name: "Damenviertel", postalCode: "07743" },
			{ name: "Westviertel", postalCode: "07743" },
			{ name: "Nord", postalCode: "07743" },
			{ name: "Löbstedt", postalCode: "07743" },
			{ name: "Winzerla", postalCode: "07745" },
			{ name: "Lobeda", postalCode: "07747" },
			{ name: "Wenigenjena", postalCode: "07749" },
			{ name: "Ziegenhain", postalCode: "07749" },
		],
		streets: [
			"Westbahnhofstraße",
			"Dornburger Straße",
			"Karl-Liebknecht-Straße",
			"Erfurter Straße",
			"Lutherstraße",
			"Kahlaische Straße",
			"Magdelstieg",
			"Camsdorfer Ufer",
			"Wöllnitzer Straße",
			"Löbstedter Straße",
			"Forstweg",
		],
		salePerM2: { apartment: [3300, 4800], house: [3100, 4400] },
		rentPerM2: [9.5, 13.5],
		transitStop: "Straßenbahnhaltestelle",
		locationHighlight:
			"Universität, Universitätsklinikum und zahlreiche Technologieunternehmen sind gut angebunden, und das Saaletal lädt zu Ausflügen ein.",
	},
	{
		name: "Gotha",
		shortName: "Gotha",
		propertyCount: 40,
		isMetropolitan: false,
		districts: [
			{ name: "Innenstadt", postalCode: "99867" },
			{ name: "Westviertel", postalCode: "99867" },
			{ name: "Ostviertel", postalCode: "99867" },
			{ name: "Siebleben", postalCode: "99867" },
			{ name: "Sundhausen", postalCode: "99867" },
		],
		streets: [
			"Friedrichstraße",
			"Erfurter Landstraße",
			"Eisenacher Straße",
			"Seebergstraße",
			"Mozartstraße",
			"Bürgeraue",
			"Huttenstraße",
			"Reinhardsbrunner Straße",
			"Waltershäuser Straße",
		],
		salePerM2: { apartment: [1700, 2700], house: [1800, 2800] },
		rentPerM2: [6.2, 8.4],
		transitStop: "Straßenbahnhaltestelle",
		locationHighlight:
			"Schloss Friedenstein und die historische Innenstadt sind in wenigen Minuten erreichbar, die Thüringerwaldbahn führt direkt in den Thüringer Wald.",
	},
	{
		name: "Eisenach",
		shortName: "Eisenach",
		propertyCount: 28,
		isMetropolitan: false,
		districts: [
			{ name: "Innenstadt", postalCode: "99817" },
			{ name: "Südviertel", postalCode: "99817" },
			{ name: "Nordstadt", postalCode: "99817" },
			{ name: "Westvorstadt", postalCode: "99817" },
		],
		streets: [
			"Karlstraße",
			"Wartburgallee",
			"Marienstraße",
			"Clemensstraße",
			"Katharinenstraße",
			"Mühlhäuser Straße",
			"Frauenberg",
		],
		salePerM2: { apartment: [1700, 2700], house: [1800, 2900] },
		rentPerM2: [6.3, 8.5],
		transitStop: "Bushaltestelle",
		locationHighlight:
			"Die Wartburg und die Wanderwege des Thüringer Waldes liegen ganz in der Nähe, die Autobahn A4 ist schnell erreichbar.",
	},
	{
		name: "Gera",
		shortName: "Gera",
		propertyCount: 28,
		isMetropolitan: false,
		districts: [
			{ name: "Innenstadt", postalCode: "07545" },
			{ name: "Untermhaus", postalCode: "07548" },
			{ name: "Debschwitz", postalCode: "07548" },
			{ name: "Bieblach", postalCode: "07546" },
			{ name: "Lusan", postalCode: "07549" },
			{ name: "Zwötzen", postalCode: "07551" },
			{ name: "Langenberg", postalCode: "07552" },
		],
		streets: [
			"Sorge",
			"Leipziger Straße",
			"Wiesestraße",
			"Heinrichstraße",
			"Humboldtstraße",
			"De-Smit-Straße",
			"Schloßstraße",
			"Zeitzer Straße",
		],
		salePerM2: { apartment: [1100, 1900], house: [1300, 2200] },
		rentPerM2: [5.3, 7],
		transitStop: "Straßenbahnhaltestelle",
		locationHighlight:
			"Die Innenstadt, der Hofwiesenpark und die Weiße Elster sind gut erreichbar.",
	},
	{
		name: "Arnstadt",
		shortName: "Arnstadt",
		propertyCount: 18,
		isMetropolitan: false,
		districts: [
			{ name: "Innenstadt", postalCode: "99310" },
			{ name: "Rabenhold", postalCode: "99310" },
			{ name: "West", postalCode: "99310" },
			{ name: "Ost", postalCode: "99310" },
		],
		streets: [
			"Ichtershäuser Straße",
			"Rosenstraße",
			"Karl-Marx-Straße",
			"Lindenallee",
			"Gothaer Straße",
			"Bahnhofstraße",
		],
		salePerM2: { apartment: [1800, 2700], house: [1900, 2900] },
		rentPerM2: [6.5, 8.4],
		transitStop: "Bushaltestelle",
		locationHighlight:
			"Die historische Altstadt ist nah, und mit der Bahn erreichen Sie Erfurt in rund 20 Minuten.",
	},
	{
		name: "Ilmenau",
		shortName: "Ilmenau",
		propertyCount: 18,
		isMetropolitan: false,
		districts: [
			{ name: "Zentrum", postalCode: "98693" },
			{ name: "Pörlitzer Höhe", postalCode: "98693" },
			{ name: "Unterpörlitz", postalCode: "98693" },
			{ name: "Langewiesen", postalCode: "98704" },
		],
		streets: [
			"Lindenstraße",
			"Karl-Zink-Straße",
			"Ehrenbergstraße",
			"Langewiesener Straße",
			"Weimarer Straße",
			"Am Stollen",
		],
		salePerM2: { apartment: [1700, 2600], house: [1800, 2800] },
		rentPerM2: [6.8, 8.9],
		transitStop: "Bushaltestelle",
		locationHighlight:
			"Die Technische Universität und die Wanderwege des Thüringer Waldes sind nicht weit, die A71 liegt direkt vor der Stadt.",
	},
	{
		name: "Apolda",
		shortName: "Apolda",
		propertyCount: 10,
		isMetropolitan: false,
		districts: [
			{ name: "Zentrum", postalCode: "99510" },
			{ name: "Nord", postalCode: "99510" },
			{ name: "Herressen", postalCode: "99510" },
		],
		streets: [
			"Bahnhofstraße",
			"Dornburger Straße",
			"Utenbacher Straße",
			"Robert-Koch-Straße",
		],
		salePerM2: { apartment: [1300, 2100], house: [1500, 2400] },
		rentPerM2: [5.8, 7.4],
		transitStop: "Bushaltestelle",
		locationHighlight:
			"Mit dem Regionalzug sind Weimar und Jena schnell erreichbar.",
	},
	{
		name: "Leipzig",
		shortName: "Leipzig",
		propertyCount: 40,
		isMetropolitan: true,
		districts: [
			{ name: "Zentrum-Süd", postalCode: "04107" },
			{ name: "Südvorstadt", postalCode: "04275" },
			{ name: "Connewitz", postalCode: "04277" },
			{ name: "Gohlis", postalCode: "04155" },
			{ name: "Waldstraßenviertel", postalCode: "04105" },
			{ name: "Plagwitz", postalCode: "04229" },
			{ name: "Schleußig", postalCode: "04229" },
			{ name: "Lindenau", postalCode: "04177" },
			{ name: "Reudnitz", postalCode: "04317" },
		],
		streets: [
			"Karl-Liebknecht-Straße",
			"Könneritzstraße",
			"Georg-Schwarz-Straße",
			"Gohliser Straße",
			"Kochstraße",
			"Waldstraße",
			"Stockartstraße",
			"Karl-Heine-Straße",
			"Holbeinstraße",
		],
		salePerM2: { apartment: [3200, 4700], house: [3200, 4600] },
		rentPerM2: [8.5, 12.5],
		transitStop: "Straßenbahnhaltestelle",
		locationHighlight:
			"Die Innenstadt ist mit Straßenbahn oder Fahrrad schnell erreichbar, Parks und die Leipziger Seen laden zur Erholung ein.",
	},
	{
		name: "Dresden",
		shortName: "Dresden",
		propertyCount: 28,
		isMetropolitan: true,
		districts: [
			{ name: "Äußere Neustadt", postalCode: "01099" },
			{ name: "Innere Neustadt", postalCode: "01097" },
			{ name: "Striesen", postalCode: "01309" },
			{ name: "Blasewitz", postalCode: "01277" },
			{ name: "Johannstadt", postalCode: "01307" },
			{ name: "Plauen", postalCode: "01187" },
			{ name: "Löbtau", postalCode: "01159" },
			{ name: "Pieschen", postalCode: "01127" },
		],
		streets: [
			"Alaunstraße",
			"Königsbrücker Straße",
			"Tolkewitzer Straße",
			"Schandauer Straße",
			"Kesselsdorfer Straße",
			"Leipziger Straße",
			"Pfotenhauerstraße",
			"Bautzner Straße",
			"Wormser Straße",
		],
		salePerM2: { apartment: [3300, 4800], house: [3300, 4800] },
		rentPerM2: [8.6, 12.6],
		transitStop: "Straßenbahnhaltestelle",
		locationHighlight:
			"Die Elbwiesen und die Altstadt sind schnell erreichbar, Cafés und kleine Läden liegen in der Nachbarschaft.",
	},
	{
		name: "Halle (Saale)",
		shortName: "Halle",
		propertyCount: 18,
		isMetropolitan: true,
		districts: [
			{ name: "Paulusviertel", postalCode: "06114" },
			{ name: "Giebichenstein", postalCode: "06114" },
			{ name: "Altstadt", postalCode: "06108" },
			{ name: "Kröllwitz", postalCode: "06120" },
			{ name: "Glaucha", postalCode: "06110" },
		],
		streets: [
			"Große Ulrichstraße",
			"Ludwig-Wucherer-Straße",
			"Burgstraße",
			"Reilstraße",
			"Merseburger Straße",
			"Advokatenweg",
			"Lessingstraße",
		],
		salePerM2: { apartment: [2200, 3300], house: [2300, 3400] },
		rentPerM2: [6.9, 9.6],
		transitStop: "Straßenbahnhaltestelle",
		locationHighlight:
			"Die Saale mit ihren Uferwegen und die Innenstadt liegen in bequemer Entfernung.",
	},
	{
		name: "Berlin",
		shortName: "Berlin",
		propertyCount: 14,
		isMetropolitan: true,
		districts: [
			{ name: "Prenzlauer Berg", postalCode: "10437" },
			{ name: "Friedrichshain", postalCode: "10245" },
			{ name: "Kreuzberg", postalCode: "10961" },
			{ name: "Neukölln", postalCode: "12047" },
			{ name: "Mitte", postalCode: "10115" },
			{ name: "Pankow", postalCode: "13187" },
			{ name: "Steglitz", postalCode: "12165" },
		],
		streets: [
			"Schönhauser Allee",
			"Kastanienallee",
			"Boxhagener Straße",
			"Bergmannstraße",
			"Weserstraße",
			"Florastraße",
			"Schloßstraße",
			"Torstraße",
		],
		salePerM2: { apartment: [5200, 8000], house: [4800, 7500] },
		rentPerM2: [13.5, 21],
		transitStop: "U-Bahn-Station",
		locationHighlight:
			"Cafés, Restaurants und kleine Läden prägen die Nachbarschaft, und über das S-Bahn-Netz sind alle Teile der Stadt schnell erreichbar.",
	},
	{
		name: "München",
		shortName: "München",
		propertyCount: 8,
		isMetropolitan: true,
		districts: [
			{ name: "Schwabing", postalCode: "80799" },
			{ name: "Maxvorstadt", postalCode: "80333" },
			{ name: "Haidhausen", postalCode: "81667" },
			{ name: "Au", postalCode: "81541" },
			{ name: "Sendling", postalCode: "81369" },
			{ name: "Isarvorstadt", postalCode: "80469" },
		],
		streets: [
			"Leopoldstraße",
			"Türkenstraße",
			"Wörthstraße",
			"Lindwurmstraße",
			"Hohenzollernstraße",
			"Fraunhoferstraße",
		],
		salePerM2: { apartment: [8800, 12500], house: [8000, 11500] },
		rentPerM2: [19.5, 26.5],
		transitStop: "U-Bahn-Station",
		locationHighlight:
			"Die Innenstadt und die Isarauen sind schnell erreichbar, Biergärten und Cafés liegen in der Nachbarschaft.",
	},
	{
		name: "Hamburg",
		shortName: "Hamburg",
		propertyCount: 10,
		isMetropolitan: true,
		districts: [
			{ name: "Eimsbüttel", postalCode: "20257" },
			{ name: "Ottensen", postalCode: "22765" },
			{ name: "Winterhude", postalCode: "22303" },
			{ name: "Eppendorf", postalCode: "20249" },
			{ name: "Barmbek", postalCode: "22305" },
		],
		streets: [
			"Osterstraße",
			"Ottenser Hauptstraße",
			"Mühlenkamp",
			"Eppendorfer Weg",
			"Fuhlsbüttler Straße",
		],
		salePerM2: { apartment: [5800, 8500], house: [5500, 8200] },
		rentPerM2: [13.5, 19.5],
		transitStop: "U-Bahn-Station",
		locationHighlight:
			"Parks, Cafés und kleine Läden prägen das Viertel, und die Innenstadt ist schnell erreichbar.",
	},
];
