export const adminPropertiesCopy = {
	de: {
		actions: {
			archive: "Archivieren",
			delete: "Löschen",
			edit: "Bearbeiten",
			restore: "Wiederherstellen",
			view: "Details ansehen",
		},
		active: "Aktiv",
		advanced: {
			apply: "Filter anwenden",
			bathrooms: "Bäder",
			bedrooms: "Schlafzimmer",
			city: "Stadt",
			contact: "Primärer Kontakt",
			heading: "Weitere Filter",
			livingArea: "Wohnfläche (m²)",
			max: "Max.",
			min: "Min.",
			plotArea: "Grundstück (m²)",
			postalCode: "Postleitzahl",
			reset: "Filter zurücksetzen",
			rooms: "Zimmer",
			source: "Immobilienquelle",
			yearBuilt: "Baujahr",
		},
		all: "Alle",
		apartment: "Wohnung",
		archiveDialog: {
			cancel: "Abbrechen",
			confirm: "Immobilien archivieren",
			description: (count: number) =>
				`${count} ausgewählte Immobilien werden aus dem aktiven Bestand entfernt.`,
			title: "Auswahl archivieren?",
		},
		actionDialog: {
			archiveDescription:
				"Die Immobilie wird aus dem aktiven Bestand entfernt.",
			archiveTitle: "Immobilie archivieren?",
			cancel: "Abbrechen",
			deleteDescription:
				"Der Datensatz wird dauerhaft gelöscht. Der Server prüft später, ob das zulässig ist.",
			deleteTitle: "Immobilie löschen?",
			restoreDescription:
				"Die Immobilie wird wieder im aktiven Bestand angezeigt.",
			restoreTitle: "Immobilie wiederherstellen?",
		},
		archived: "Archiviert",
		bulkArchive: "Auswahl archivieren",
		clearSelection: "Auswahl aufheben",
		contact: "Kontakt",
		create: "Immobilie anlegen",
		description: "Verwalten Sie den internen Immobilienbestand der Agentur.",
		empty: "Keine Immobilien entsprechen der aktuellen Suche oder den Filtern.",
		house: "Haus",
		imageMissing: "Kein Titelbild",
		moreFilters: "Weitere Filter",
		next: "Weiter",
		noContact: "Agenturbestand",
		pageSize: "Pro Seite",
		previous: "Zurück",
		property: "Immobilie",
		results: (count: number) => `${count} Immobilien`,
		search: "Referenz, Adresse oder Kontakt suchen",
		selected: (count: number) => `${count} ausgewählt`,
		sort: {
			city_asc: "Stadt aufsteigend",
			city_desc: "Stadt absteigend",
			living_area_asc: "Wohnfläche aufsteigend",
			living_area_desc: "Wohnfläche absteigend",
			newest: "Neueste",
			oldest: "Älteste",
			recently_updated: "Zuletzt aktualisiert",
			reference_asc: "Referenz aufsteigend",
			reference_desc: "Referenz absteigend",
			rooms_asc: "Zimmer aufsteigend",
			rooms_desc: "Zimmer absteigend",
			year_built_asc: "Baujahr aufsteigend",
			year_built_desc: "Baujahr absteigend",
		},
		source: {
			AGENCY_OWNED: "Agenturbestand",
			EXTERNAL_CLIENT: "Externer Auftrag",
		},
		status: "Status",
		table: {
			address: "Adresse",
			area: "Fläche / Zimmer",
			contact: "Quelle / Kontakt",
			property: "Immobilie",
			status: "Status",
			updated: "Aktualisiert",
		},
		title: "Immobilien",
		type: "Typ",
		updated: "Aktualisiert",
		view: {
			grid: "Rasteransicht",
			label: "Darstellung",
			table: "Tabellenansicht",
		},
	},
	en: {
		actions: {
			archive: "Archive",
			delete: "Delete",
			edit: "Edit property",
			restore: "Restore",
			view: "View details",
		},
		active: "Active",
		advanced: {
			apply: "Apply filters",
			bathrooms: "Bathrooms",
			bedrooms: "Bedrooms",
			city: "City",
			contact: "Primary contact",
			heading: "More filters",
			livingArea: "Living area (m²)",
			max: "Max",
			min: "Min",
			plotArea: "Plot area (m²)",
			postalCode: "Postal code",
			reset: "Reset filters",
			rooms: "Rooms",
			source: "Property source",
			yearBuilt: "Year built",
		},
		all: "All",
		apartment: "Apartment",
		archiveDialog: {
			cancel: "Cancel",
			confirm: "Archive properties",
			description: (count: number) =>
				`${count} selected properties will be removed from the active inventory.`,
			title: "Archive selection?",
		},
		actionDialog: {
			archiveDescription:
				"The property will be removed from the active inventory.",
			archiveTitle: "Archive property?",
			cancel: "Cancel",
			deleteDescription:
				"The record will be permanently deleted. The server will later verify whether this is allowed.",
			deleteTitle: "Delete property?",
			restoreDescription: "The property will return to the active inventory.",
			restoreTitle: "Restore property?",
		},
		archived: "Archived",
		bulkArchive: "Archive selection",
		clearSelection: "Clear selection",
		contact: "Contact",
		create: "Create property",
		description: "Manage the agency's internal property inventory.",
		empty: "No properties match the current search or filters.",
		house: "House",
		imageMissing: "No cover image",
		moreFilters: "More filters",
		next: "Next",
		noContact: "Agency-owned",
		pageSize: "Per page",
		previous: "Previous",
		property: "Property",
		results: (count: number) => `${count} properties`,
		search: "Search reference, address, or contact",
		selected: (count: number) => `${count} selected`,
		sort: {
			city_asc: "City ascending",
			city_desc: "City descending",
			living_area_asc: "Living area ascending",
			living_area_desc: "Living area descending",
			newest: "Newest",
			oldest: "Oldest",
			recently_updated: "Recently updated",
			reference_asc: "Reference ascending",
			reference_desc: "Reference descending",
			rooms_asc: "Rooms ascending",
			rooms_desc: "Rooms descending",
			year_built_asc: "Year built ascending",
			year_built_desc: "Year built descending",
		},
		source: {
			AGENCY_OWNED: "Agency-owned",
			EXTERNAL_CLIENT: "External client",
		},
		status: "Status",
		table: {
			address: "Address",
			area: "Area / rooms",
			contact: "Source / contact",
			property: "Property",
			status: "Status",
			updated: "Updated",
		},
		title: "Properties",
		type: "Type",
		updated: "Updated",
		view: { grid: "Grid view", label: "Collection view", table: "Table view" },
	},
} as const;

export type AdminPropertiesCopy =
	(typeof adminPropertiesCopy)[keyof typeof adminPropertiesCopy];
