export const createListingCopy = {
	de: {
		administration: "Administration · Immobilieneinrichtung",
		apartment: "Wohnung",
		addressVisibility: "Genaue Adresse öffentlich anzeigen",
		addressVisibilityDescription:
			"Straße, Hausnummer und Einheit werden erst mit dem veröffentlichten Inserat sichtbar.",
		automaticDescription: "Verwendet die Inseratsbeschreibung",
		automaticSlug:
			"Automatisch aus dem Inseratstitel erzeugt. Das Feld oben kann den Wert überschreiben.",
		automaticTitle: "Verwendet den Inseratstitel",
		backToProperty: "Später fortsetzen",
		create: "Entwurf anlegen",
		creating: "Entwurf wird angelegt",
		customDescription: "Eigene SEO-Beschreibung",
		customSlug: "Eigener, bearbeiteter Slug",
		customTitle: "Eigener SEO-Titel",
		description: "Beschreibung",
		descriptionPlaceholder: "Beschreiben Sie die Immobilie für Interessenten.",
		heading: "Inserat anlegen",
		house: "Haus",
		listingType: "Vermarktungsart",
		livingArea: "Wohnfläche",
		loadError: "Das Inserat kann nicht vorbereitet werden.",
		loading: "Inserat wird vorbereitet …",
		price: { rent: "Monatliche Kaltmiete", sale: "Kaufpreis" },
		prefillDescription:
			"Titel, Beschreibung und Adressfreigabe wurden übernommen. Der Preis bleibt leer, da Verkauf und Vermietung unterschiedliche Beträge verwenden. Bitte prüfen Sie den Inhalt vor dem Anlegen.",
		prefillTitle: {
			rent: "Inhalte aus dem bestehenden Vermietungsinserat übernommen",
			sale: "Inhalte aus dem bestehenden Verkaufsinserat übernommen",
		},
		propertyContext: "Immobilienkontext",
		rent: "Vermietung",
		rooms: "Zimmer",
		requiredType: "Wählen Sie Verkauf oder Vermietung.",
		retry: "Erneut versuchen",
		sale: "Verkauf",
		seo: "SEO-Einstellungen",
		seoDescription: "SEO-Beschreibung (optional)",
		seoHelp:
			"Leere SEO-Felder verwenden automatisch Titel und Beschreibung des Inserats.",
		seoTitle: "SEO-Titel (optional)",
		seoPreview: "Vorschau für Suchmaschinen",
		slug: "URL-Slug (optional)",
		slugHelp: "Leer lassen, damit der Slug automatisch aus dem Titel entsteht.",
		subtitle:
			"Erstellen Sie zuerst einen Entwurf. Veröffentlicht wird erst nach der Bereitschaftsprüfung.",
		title: "Inseratstitel",
		titlePlaceholder: "Zum Beispiel: Helle Altbauwohnung in Erfurt",
		urlPreview: "Vorschau der öffentlichen URL",
		unavailableType:
			"Für diese Immobilie besteht bereits ein nicht archiviertes Inserat dieses Typs.",
		validationPrice: "Geben Sie einen Betrag größer als 0 ein.",
	},
	en: {
		administration: "Administration · Property setup",
		apartment: "Apartment",
		addressVisibility: "Show the exact address publicly",
		addressVisibilityDescription:
			"Street, house number, and unit become visible only when the listing is published.",
		automaticDescription: "Uses the listing description",
		automaticSlug:
			"Generated automatically from the listing title. The field above can override it.",
		automaticTitle: "Uses the listing title",
		backToProperty: "Finish later",
		create: "Create draft",
		creating: "Creating draft",
		customDescription: "Custom SEO description",
		customSlug: "Custom editable slug",
		customTitle: "Custom SEO title",
		description: "Description",
		descriptionPlaceholder: "Describe the property for prospective clients.",
		heading: "Create listing",
		house: "House",
		listingType: "Listing type",
		livingArea: "Living area",
		loadError: "The listing could not be prepared.",
		loading: "Preparing listing…",
		price: { rent: "Monthly base rent", sale: "Purchase price" },
		prefillDescription:
			"Title, description, and address visibility were reused. Price stays blank because Sale and Rent use different amounts. Review the content before creating the draft.",
		prefillTitle: {
			rent: "Content reused from the existing rent listing",
			sale: "Content reused from the existing sale listing",
		},
		propertyContext: "Property context",
		rent: "Rent",
		rooms: "Rooms",
		requiredType: "Choose Sale or Rent.",
		retry: "Try again",
		sale: "Sale",
		seo: "SEO settings",
		seoDescription: "SEO description (optional)",
		seoHelp:
			"Blank SEO fields automatically use the listing title and description.",
		seoTitle: "SEO title (optional)",
		seoPreview: "Search result preview",
		slug: "URL slug (optional)",
		slugHelp: "Leave blank to generate the slug automatically from the title.",
		subtitle:
			"Create a draft first. Publishing happens only after the readiness review.",
		title: "Listing title",
		titlePlaceholder: "For example: Bright period apartment in Erfurt",
		urlPreview: "Public URL preview",
		unavailableType:
			"This property already has a non-archived listing of this type.",
		validationPrice: "Enter an amount greater than 0.",
	},
} as const;
