export const createPropertyCopy = {
	de: {
		address: "Immobilientyp und Adresse",
		addressDescription:
			"Die vollständige interne Adresse bleibt unabhängig von der späteren öffentlichen Anzeige gespeichert.",
		agencyOwned: "Agenturbestand",
		apartment: "Wohnung",
		bathrooms: "Bäder",
		bedrooms: "Schlafzimmer",
		cancel: "Abbrechen",
		city: "Stadt",
		contact: {
			company: "Unternehmen (optional)",
			create: "Neuen Kontakt anlegen",
			created: "Kontakt angelegt und ausgewählt.",
			description: "Mindestens E-Mail-Adresse oder Telefonnummer angeben.",
			email: "E-Mail-Adresse",
			empty: "Kein passender Kontakt gefunden.",
			fullName: "Vollständiger Name",
			heading: "Kontakt anlegen",
			phone: "Telefonnummer",
			search: "Kontakt nach Name, Unternehmen oder E-Mail suchen",
			select: "Eigentümer auswählen",
		},
		create: "Immobilie anlegen",
		creating: "Immobilie wird angelegt",
		details: "Immobiliendaten",
		detailsDescription:
			"Flächen und Zimmerzahlen werden numerisch gespeichert; Einheiten gehören nicht in den Wert.",
		discard: "Änderungen verwerfen",
		discardDescription: "Nicht gespeicherte Eingaben gehen verloren.",
		discardTitle: "Diese Seite verlassen?",
		externalClient: "Externer Auftrag",
		floorNumber: "Etage",
		house: "Haus",
		houseNumber: "Hausnummer",
		livingArea: "Wohnfläche",
		owner: "Quelle und Eigentümer",
		ownerDescription:
			"Wählen Sie, ob die Immobilie der Agentur gehört oder für einen externen Kontakt verwaltet wird.",
		plotArea: "Grundstücksfläche",
		postalCode: "Postleitzahl",
		progress: {
			current: "Aktuell",
			images: "Bilder und Merkmale",
			listing: "Inserat",
			property: "Immobiliendaten",
			upcoming: "Danach",
		},
		propertyType: "Immobilientyp",
		rooms: "Zimmer",
		serverError:
			"Die Immobilie konnte nicht angelegt werden. Ihre Eingaben bleiben erhalten.",
		streetName: "Straße",
		success: "Immobilie angelegt. Weiter zu den Bildern für",
		title: "Immobilie anlegen",
		totalFloors: "Etagen insgesamt",
		unit: "Einheit (optional)",
		validation: {
			contact: "Für einen externen Auftrag ist ein Eigentümer erforderlich.",
			emailOrPhone: "E-Mail-Adresse oder Telefonnummer ist erforderlich.",
			integer: "Bitte eine ganze Zahl eingeben.",
			positive: "Der Wert muss größer als null sein.",
			postalCode: "Die Postleitzahl muss fünfstellig sein.",
			required: "Dieses Feld ist erforderlich.",
			year: "Bitte ein vierstelliges Baujahr zwischen 1000 und 9999 eingeben.",
		},
		yearBuilt: "Baujahr",
	},
	en: {
		address: "Property type and address",
		addressDescription:
			"The complete internal address is stored independently from its later public visibility.",
		agencyOwned: "Agency-owned",
		apartment: "Apartment",
		bathrooms: "Bathrooms",
		bedrooms: "Bedrooms",
		cancel: "Cancel",
		city: "City",
		contact: {
			company: "Company (optional)",
			create: "Create new contact",
			created: "Contact created and selected.",
			description: "Provide at least an email address or phone number.",
			email: "Email address",
			empty: "No matching contact found.",
			fullName: "Full name",
			heading: "Create contact",
			phone: "Phone number",
			search: "Search contacts by name, company, or email",
			select: "Select owner",
		},
		create: "Create property",
		creating: "Creating property",
		details: "Property details",
		detailsDescription:
			"Areas and room counts are stored as numbers; units do not belong in the editable value.",
		discard: "Discard changes",
		discardDescription: "Your unsaved property information will be lost.",
		discardTitle: "Leave this page?",
		externalClient: "External client",
		floorNumber: "Floor number",
		house: "House",
		houseNumber: "House number",
		livingArea: "Living area",
		owner: "Source and owner",
		ownerDescription:
			"Choose whether the agency owns this property or manages it for an external contact.",
		plotArea: "Plot area",
		postalCode: "Postal code",
		progress: {
			current: "Current",
			images: "Images and features",
			listing: "Listing",
			property: "Property record",
			upcoming: "Upcoming",
		},
		propertyType: "Property type",
		rooms: "Rooms",
		serverError:
			"The property could not be created. Your entered values remain available.",
		streetName: "Street name",
		success: "Property created. Continue with images for",
		title: "Create property",
		totalFloors: "Total floors",
		unit: "Unit number (optional)",
		validation: {
			contact: "An owner is required for an external client property.",
			emailOrPhone: "An email address or phone number is required.",
			integer: "Enter a whole number.",
			positive: "The value must be greater than zero.",
			postalCode: "Postal code must contain five digits.",
			required: "This field is required.",
			year: "Enter a four-digit year between 1000 and 9999.",
		},
		yearBuilt: "Year built",
	},
} as const;

export type CreatePropertyCopy =
	(typeof createPropertyCopy)[keyof typeof createPropertyCopy];
