/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../routes/__root'
import { Route as MarketingIndexRouteImport } from './../routes/_marketing/index'
import { Route as ApiSplatRouteImport } from './../routes/api.$'
import { Route as MarketingPropertiesRouteImport } from './../routes/_marketing/properties'

const MarketingIndexRoute = MarketingIndexRouteImport.update({
  id: '/_marketing/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingPropertiesRoute = MarketingPropertiesRouteImport.update({
  id: '/_marketing/properties',
  path: '/properties',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/properties': typeof MarketingPropertiesRoute
  '/api/$': typeof ApiSplatRoute
  '/': typeof MarketingIndexRoute
}
export interface FileRoutesByTo {
  '/properties': typeof MarketingPropertiesRoute
  '/api/$': typeof ApiSplatRoute
  '/': typeof MarketingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_marketing/properties': typeof MarketingPropertiesRoute
  '/api/$': typeof ApiSplatRoute
  '/_marketing/': typeof MarketingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/properties' | '/api/$' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/properties' | '/api/$' | '/'
  id: '__root__' | '/_marketing/properties' | '/api/$' | '/_marketing/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MarketingPropertiesRoute: typeof MarketingPropertiesRoute
  ApiSplatRoute: typeof ApiSplatRoute
  MarketingIndexRoute: typeof MarketingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_marketing/': {
      id: '/_marketing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MarketingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing/properties': {
      id: '/_marketing/properties'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof MarketingPropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  MarketingPropertiesRoute: MarketingPropertiesRoute,
  ApiSplatRoute: ApiSplatRoute,
  MarketingIndexRoute: MarketingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
